name: Build

on:
  push:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  packages: write

jobs:
  generate-images-matrix:
    name: images matrix
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.generate-images-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Generate images matrix
        id: generate-images-matrix
        run: echo "matrix={\"images\":[$(ls -mQ images)]}" | tee $GITHUB_OUTPUT

  build-images:
    name: ${{ matrix.image }} image
    needs: generate-images-matrix
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.generate-images-matrix.outputs.matrix).images }}
    uses: ./.github/workflows/build-image.yaml
    with:
      image: ${{ matrix.image }}
    secrets: inherit
