name: Build

on:
  push:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  packages: write

jobs:
  generate-images-matrix:
    name: images matrix
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.generate-images-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Generate images matrix
        id: generate-images-matrix
        run: echo "matrix={\"images\":[$(ls -mQ images)]}" | tee $GITHUB_OUTPUT

  build-images:
    name: ${{ matrix.image }} image
    needs: generate-images-matrix
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.generate-images-matrix.outputs.matrix).images }}
    uses: ./.github/workflows/build-image.yaml
    with:
      image: ${{ matrix.image }}
    secrets: inherit
